use_frameworks!

platform :ios, '11.0'

target 'ReactNativeCallInvoker_Example' do
  pod 'ReactNativeCallInvoker', :path => '../'

  target 'ReactNativeCallInvoker_Tests' do
    inherit! :search_paths

    
  end
end
